const express = require('express');
const nodemailer = require('nodemailer');
const { google } = require('googleapis');
const app = express();
app.set("view engine","ejs");

const port = 3000;

const CLIENT_ID = '793498554635-dkd2pm728anr2ep1guqvrs9fk63e4c3e.apps.googleusercontent.com';
const CLIENT_SECRET = client_secret; // here you use client secret from google cloud console
const REDIRECT_URI = 'https://developers.google.com/oauthplayground';
const REFRESH_TOKEN = refresh_token; // here refresh token is generated by REDIRECT URI 

const oAuth2Client = new google.auth.OAuth2(CLIENT_ID,CLIENT_SECRET,REDIRECT_URI);

oAuth2Client.setCredentials({ refresh_token: REFRESH_TOKEN });

/*
Now to use my GMail API 
Here I am using nodemailer a npm module to send email
1. Done with google cloud console and got CLIENT_ID and CLIENT SECRET from it
2. In https://developers.google.com/oauthplayground scopes blank paste https://mail.google.com and in OAuth credentials paste the CLIENT_ID and CLIENT_SECRET (from the google cloud console) and click authorize  
3. you will be redirected to authorize with your gmail account to sign in  (uses OAuth2) 
4. This node js code will be used to send the email with all the required things filled.
5. By running it You mail will be sent from your authorize email id to destinate email id( what you write in <to> in mailOptions code)

*/

function sendEmail(usermail){

    
    const accessToken = oAuth2Client.getAccessToken();
    // to generate accessTokens every time

    // create reusable transporter object
    let transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
        type: 'OAuth2',
        user: usermail,
        clientId: CLIENT_ID,
        clientSecret: CLIENT_SECRET,
        refreshToken: REFRESH_TOKEN,
        accessToken: accessToken
        }
    });

    
    // send mail with defined transport object
    // mail options to know to,subject, text to sent
    let mailOptions = {
        from: usermail,
        to : 'avinashkethireddy2001@gmail.com', // destination email id
        subject: 'Sending via GMAIL API TESTING  ',
        text: 'Hi Avinash, I think its working !'
    };

    // Delivering the message object using the sendMail() method of your previously created transporter
    transporter.sendMail(mailOptions, function(err, data) {
        if (err) {
        console.log("Error " + err);
        } else {
        console.log("Email sent successfully");
        }
    });
    
}

app.get("/",function(req,res){
    sendEmail('avinashreddy482001@gmail.com'); // authorized email id
    res.render("home");
});


app.listen(port, () => {
  console.log(`Project listening at http://localhost:${port}`)
})